name: Validate Dev Build

on:
  pull_request:
    branches:
      - 'development'


jobs:
    build-only:
        name: Dev - PR Build Verification
        runs-on: ubuntu-latest
        steps:
            - name: Checkout Repo
              uses: actions/checkout@master

            - name: Initialize Node and Cache Dependencies
              uses: actions/setup-node@master
              with:
                  node-version: 20
                  cache: 'npm'
                  cache-dependency-path: package-lock.json

            - name: Install Dependencies
              run: npm install

            - name: Build Development App
              run: npm run build

            - run: echo "PR Build Verification Successful!"